version: 2.1

executors:
  node-10:
    docker:
      - image: circleci/node:10

commands:
  test_example_project:
    description: "Tests the compilation of a specified example"
    parameters:
      dir:
        type: string
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - run: yarn link
      - run: yarn --cwd=examples/<< parameters.dir >> --frozen-lockfile
      - run: yarn --cwd=examples/<< parameters.dir >> link nexus
      - run: yarn --cwd=examples/<< parameters.dir >> tsc

jobs:
  nexus:
    executor: node-10
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn codecov
      - store_artifacts:
          path: coverage

  example_apollo-fullstack:
    executor: node-10
    steps:
      - test_example_project:
          dir: "apollo-fullstack"

  example_ghost:
    executor: node-10
    steps:
      - test_example_project:
          dir: "ghost"

  example_githunt-api:
    docker:
      - image: circleci/node:8
    steps:
      - test_example_project:
          dir: "githunt-api"

  example_kitchen-sink:
    executor: node-10
    steps:
      - test_example_project:
          dir: "kitchen-sink"

  example_star-wars:
    executor: node-10
    steps:
      - test_example_project:
          dir: "star-wars"
      - run:
          command: |
            rm examples/star-wars/src/star-wars-typegen.ts
            rm examples/star-wars/star-wars-schema.graphql
            node examples/star-wars/dist/schema.js
            git diff --exit-code

  example_ts-ast-reader:
    executor: node-10
    steps:
      - test_example_project:
          dir: "ts-ast-reader"

workflows:
  nexus:
    jobs:
      - nexus
      - example_apollo-fullstack
      - example_ghost
      - example_githunt-api
      - example_kitchen-sink
      - example_star-wars
      - example_ts-ast-reader
